import Header from "@/components/header";
import LeftSidebar from "@/components/leftsidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Alma-Mater</title>
      </head>
      <body className="flex font-sans h-screen bg-background text-foreground">

        <main className={inter.className}>
          <Header />
          <div className="flex bg-offBlack text-lightGray p-6 h-full w-full">
            <LeftSidebar />
            {children}
            {/* <RightSidebar /> */}
          </div>
        </main>

      </body>
    </html>
  );
}
